### ISSUE TITLE
第一次运行出了错

### ISSUE THREAD

**Issue by xzghua** [FloydaGithub/fake-commit#2]
```
Info] 2017-09-14 07:28:08.201786
[Info] Fake Commit Began ...
Traceback (most recent call last):
  File "fake-commit.py", line 136, in <module>
    main()
  File "fake-commit.py", line 128, in main
    gh = github3.login(Config.user_name, password=Config.user_passwd)
AttributeError: 'module' object has no attribute 'login'
```

求告知...

**Comment by floydawong** [comment]
看报错应该是你没安装github3这个库.
pip install github3.py

CONFIG_FILE = "Config.py"
CONFIG_DEFAULT = """
user_name      = "<user_name>"
user_passwd    = "<user_passwd>"
fake_repo_name = "fake-commit-log"
"""

然后在Config.py文件里面, 填写账号密码和仓库的名字.
