### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by haobowd** [FloydaGithub/fake-commit#3]
[Info] 2018-03-16 11:59:39.121969
[Info] Fake Commit Began ...
Traceback (most recent call last):
  File "fake-commit.py", line 136, in <module>
    main()
  File "fake-commit.py", line 129, in main
    if DEBUG or not has_commit_today():
  File "fake-commit.py", line 56, in has_commit_today
    repos = github3.iter_user_repos(Config.user_name)
AttributeError: 'module' object has no attribute 'iter_user_repos'

**Comment by floydawong** [comment]
pip install github3.py
